
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Backend.Analizadores;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int MENOS = 8;
  public static final int CADENA = 3;
  public static final int SUMA = 4;
  public static final int MULTI = 6;
  public static final int ETIQUETAS = 24;
  public static final int EJECUTAR = 32;
  public static final int PORCENTAJE = 30;
  public static final int TIPO = 27;
  public static final int DOS_PUNTOS = 12;
  public static final int VALORES = 25;
  public static final int BARRAS = 19;
  public static final int COMA = 13;
  public static final int TOTAL = 28;
  public static final int EOF = 0;
  public static final int DEF = 18;
  public static final int PIE = 20;
  public static final int DIV = 7;
  public static final int EXTRA = 31;
  public static final int CANTIDAD = 29;
  public static final int PARENTESIS_C = 15;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int PARENTESIS_A = 14;
  public static final int LLAVE_C = 11;
  public static final int EJEY = 23;
  public static final int LLAVE_A = 10;
  public static final int PUNTO_COMA = 9;
  public static final int EJEX = 22;
  public static final int CORCHETE_C = 17;
  public static final int UNIR = 26;
  public static final int CORCHETE_A = 16;
  public static final int TITULO = 21;
  public static final int RESTA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "CADENA",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "MENOS",
  "PUNTO_COMA",
  "LLAVE_A",
  "LLAVE_C",
  "DOS_PUNTOS",
  "COMA",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "CANTIDAD",
  "PORCENTAJE",
  "EXTRA",
  "EJECUTAR"
  };

  /* non terminals */
  static final int paramPie = 9;
  static final int segundaSeccion = 15;
  static final int cuerpoPie = 8;
  static final int atribPie = 10;
  static final int atribBarra = 7;
  static final int listaCadenas = 12;
  static final int inicio = 0;
  static final int primerseccion = 1;
  static final int grafico = 3;
  static final int paramBarra = 5;
  static final int valNumerico = 14;
  static final int definicion = 2;
  static final int elTipo = 11;
  static final int exe = 16;
  static final int listaNumeros = 13;
  static final int tupla = 6;
  static final int cuerpoBarra = 4;
}

